### ISSUE TITLE
 请问下该项目的功能和使用

### ISSUE THREAD

**Issue by shixueqian** [nothot/DUALive#1]
最近需要做一个录屏直播的功能，将手机上的屏幕内容直播到Facebook上。我看到您的这个项目可以实现这个功能，但是我跑起来之后无法看到直播的效果。请问下您这个项目是可以在iOS上录制屏幕，然后将屏幕直播到Facebook上面去的吗？那我该如何检验检验效果呢？直播地址是什么？哪里可以看到？大神方便的话加我的QQ（274526379）帮个忙，感激不尽！

**Comment by nothot** [comment]
这个项目是录制屏幕，并直播到Facebook上。不能看到效果是因为demo里默认使用了一个测试的url，我已经更新了demo，现在运行会正常调起Facebook进行直播。直播的地址是通过Facebook的API获得的，请注意使用你的Facebook开发者账号。
